### ISSUE TITLE
[03-git-github-and-markdown] Branch name is not identical

### ISSUE THREAD

**Issue by lentidas** [heig-vd-dai-course/heig-vd-dai-course#242]
During the practical work followed on [this course material file](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md), I noticed that some of the branch names are not the same during the guide.

For example, in [this section](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#create-a-new-branch) we create a branch called `add-myself-to-the-list-of-students`, but later, in [this section](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#intentionally-create-a-conflict), you reference that we need to checkout the branch called `add-myself-github-username-to-the-list-of-students`.

I also think in [this line](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/e57a2205b48ce2a435624adbb713d83e30b408b0/03-git-github-and-markdown/COURSE_MATERIAL.md?plain=1#L1410) the branch `change-title-of-readme-file` should be `this-branch-will-create-a-conflict`.

**Comment by ludelafo** [comment]
Dear @lentidas,

Thank you very much for all your issues! I guess that's why people weren't having the intentional conflict.

A new PR was opened and my colleagues will review it as soon as possible to integrate all the elements you have identified: <https://github.com/heig-vd-dai-course/heig-vd-dai-course/pull/264>.

Thank you again and looking forward to next week!
Ludovic
